install(
    TARGETS scidup_main
    RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}" )

set(
    SCIDUP_DATA_INSTALL_DIR
    "${CMAKE_INSTALL_DATADIR}/scid-up" )

install(
    DIRECTORY "${CMAKE_SOURCE_DIR}/resources/bitmaps"
    DESTINATION "${SCIDUP_DATA_INSTALL_DIR}" )
install(
    DIRECTORY "${CMAKE_SOURCE_DIR}/resources/bitmaps2"
    DESTINATION "${SCIDUP_DATA_INSTALL_DIR}" )
install(
    DIRECTORY "${CMAKE_SOURCE_DIR}/resources/books"
    DESTINATION "${SCIDUP_DATA_INSTALL_DIR}" )
install(
    DIRECTORY "${CMAKE_SOURCE_DIR}/resources/html"
    DESTINATION "${SCIDUP_DATA_INSTALL_DIR}" )
install(
    DIRECTORY "${CMAKE_SOURCE_DIR}/resources/help"
    DESTINATION "${SCIDUP_DATA_INSTALL_DIR}" )
install(
    DIRECTORY "${CMAKE_SOURCE_DIR}/resources/img"
    DESTINATION "${SCIDUP_DATA_INSTALL_DIR}" )
install(
    DIRECTORY "${CMAKE_SOURCE_DIR}/scripts"
    DESTINATION "${SCIDUP_DATA_INSTALL_DIR}" )
install(
    DIRECTORY "${CMAKE_SOURCE_DIR}/resources/sounds"
    DESTINATION "${SCIDUP_DATA_INSTALL_DIR}" )
install(
    DIRECTORY "${CMAKE_SOURCE_DIR}/tcl"
    DESTINATION "${SCIDUP_DATA_INSTALL_DIR}" )

file(
    GLOB ECO_FILES
    CONFIGURE_DEPENDS
    "${CMAKE_SOURCE_DIR}/*.eco" )
install(
    FILES ${ECO_FILES}
    DESTINATION "${SCIDUP_DATA_INSTALL_DIR}" )
